CREATE TABLE IF NOT EXISTS users (
	user_id SERIAL NOT NULL PRIMARY KEY
	, username VARCHAR (255) NOT NULL
	, age INTEGER
	, email VARCHAR (255) NOT NULL
	, password VARCHAR (255) NOT NULL
	, auth VARCHAR (255) NOT NULL
	, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
	, updated_at TIMESTAMPTZ DEFAULT NULL
	, deleted_at TIMESTAMPTZ DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS blogs (
	blog_id SERIAL NOT NULL PRIMARY KEY
	, title VARCHAR (255) NOT NULL
	, content VARCHAR (3000) NOT NULL
	, user_id INTEGER NOT NULL
	, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
	, updated_at TIMESTAMPTZ DEFAULT NULL
	, deleted_at TIMESTAMPTZ DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS comments (
	comment_id SERIAL NOT NULL PRIMARY KEY
	, blog_id INTEGER
	, content VARCHAR (200)
	, from_user_id INTEGER
	, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
	, updated_at TIMESTAMPTZ DEFAULT NULL
	, deleted_at TIMESTAMPTZ DEFAULT NULL
);
